include: package:very_good_analysis/analysis_options.5.1.0.yaml

formatter:
  trailing_commas: preserve

analyzer:
  exclude:
    - lib/src/core/l10n/generated_localizations/**
    - lib/src/core/l10n/*.arb
    - code_generators/**
    - "**/*.g.dart"

  errors:
    inference_failure_on_instance_creation: ignore
    inference_failure_on_function_invocation: ignore
    depend_on_referenced_packages: ignore

linter:
  rules:
    public_member_api_docs: false
    always_use_package_imports: false
    lines_longer_than_80_chars: false
    sort_constructors_first: false
    unnecessary_await_in_return: false
    cascade_invocations: false
    eol_at_end_of_file: false
    avoid_dynamic_calls: false
    always_put_required_named_parameters_first: false
    omit_local_variable_types: false
    avoid_slow_async_io: false
    flutter_style_todos: false
    use_if_null_to_convert_nulls_to_bools: false
    # await_only_futures does not consideer records
    await_only_futures: false
