arb-dir: lib/src/core/l10n
template-arb-file: app_en.arb
output-localization-file: lesa_localizations.dart
output-class: LesaLocalizations
output-dir: lib/src/core/l10n/generated_localizations
synthetic-package: false
